name: morepicks
version: '${project.version}'
main: com.scuffeditalian.morepicks.Morepicks
api-version: 1.19
commands:
  GiveAllPicks:
    aliases:
      - gap
    description: gives all the pick items of the morepicks plugin
    permission: op
  GiveAllDusts:
    aliases:
      - gad
    description: gives all dust items of the Morepicks plugin
    permission: op
